export const actions ={
    profile:{
        "DATA_FETCHING": "PROFILE_DATA_FETCHING",
        "DATA_FETCHED": "PROFILE_DATA_FETCHED",
        "DATA_FETCH_ERROR": "PROFILE_DATA_FETCH_ERROR",
        "USER_DATA_EDITED": "PROFILE_USER_DATA_EDITED",
        "IMAGE_UPDATED": "PROFILE_IMAGE_UPDATED",
        "PROFILE_POST_DELETED": "PROFILE_POST_DELETED",
    },

    post:{
        "DATA_FETCHING": "POST_DATA_FETCHING",
        "DATA_FETCHED": "POST_DATA_FETCHED",
        "DATA_FETCH_ERROR": "POST_DATA_FETCH_ERROR",
        "USER_DATA_EDITED": "POST_USER_DATA_EDITED",
        "IMAGE_UPDATED": "POST_IMAGE_UPDATED",
        "POST_CREATED": "POST_CREATED",
        "POST_DELETED": "POST_DELETED",
    }
}